#!/usr/bin/env bash
# FuneralOS — assembles each native app's www/ bundle from the shared saas/
# source tree (single source of truth — nothing in native/*/www is
# hand-edited, it's all regenerated by this script). Run before `npx cap
# sync` whenever saas/ changes and you want those changes in the next native
# build, or before pushing an OTA update via Capgo (native/publish-ota.sh).
#
# Deliberately excludes saas/sw.js and the manifest.webmanifest files —
# Service Worker / PWA-install concepts don't apply inside a Capacitor
# WebView; Capgo covers the "get updates without a store review" role
# instead. Also excludes saas/gr/, saas/es/, saas/it/ (marketing landing
# pages, not part of the logged-in app) and saas/admin.html (owner-only web
# tool, not shipped in either native app).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SAAS="$REPO_ROOT/saas"
NATIVE="$REPO_ROOT/native"

# Both editions load supabase-js from jsDelivr on the web. That's fine there
# (always online, and the CDN copy is cached across the whole site), but
# inside a native WebView it makes the app's boot a hard dependency on the
# network: every consumer destructures the global at the top level
# (`const { createClient } = window.supabase` — saas/freemium.js,
# saas/en/freemium.js, login.html, ...), so if the CDN request fails, is
# blocked, or just hasn't finished, that line throws a TypeError and takes
# the whole auth guard down with it. The loading overlay is then never
# removed and the app sits on a blank screen with no visible error.
#
# Vendoring the identical UMD bundle into the binary (saas/vendor/supabase.js)
# makes the native boot work with no network at all, and removes a real
# store-review risk — a reviewer on a throttled or restricted network would
# otherwise open a dead app. Only the URL is rewritten; the global the bundle
# defines (`supabase`) is the same either way, so no other code changes.
# The web deploy is untouched and keeps using the CDN.
vendor_supabase() {
  local dest="$1"
  cp "$SAAS/vendor/supabase.js" "$dest/supabase.js"
  perl -pi \
    -e 's{https://cdn\.jsdelivr\.net/npm/\@supabase/supabase-js\@2}{supabase.js}g;' \
    "$dest"/*.html
}

# native-boot-debug.js goes in as the very first script of the entry HTML, so
# it is installed before freemium.js/app.js can throw. Without it a fatal boot
# error is invisible: the app just sits on its loading overlay and the Xcode
# console says only "JS Eval error A JavaScript exception occurred", with no
# message, file, or line. See the header comment in saas/native-boot-debug.js.
inject_boot_debug() {
  local dest="$1"
  cp "$SAAS/native-boot-debug.js" "$dest/"
  perl -0pi \
    -e 's{<head>}{<head>\n  <script src="native-boot-debug.js"></script>};' \
    "$dest/index.html"
}

build_gr() {
  local dest="$NATIVE/gr-app/www"
  echo "Building GR www/ -> $dest"
  rm -rf "$dest"
  mkdir -p "$dest"

  cp "$SAAS/app.html" "$dest/index.html"
  cp "$SAAS/login.html" "$dest/login.html"
  cp "$SAAS/reset.html" "$dest/reset.html" 2>/dev/null || true
  cp "$SAAS/privacy.html" "$dest/privacy.html"
  cp "$SAAS/terms.html" "$dest/terms.html"
  cp "$SAAS/styles.css" "$dest/"
  cp "$SAAS/config.js" "$dest/"
  cp "$SAAS/freemium.js" "$dest/"
  cp "$SAAS/app.js" "$dest/"
  cp "$SAAS/suppliers.js" "$dest/"
  cp "$SAAS/gr-documents.js" "$dest/"
  cp "$SAAS/native-bridge.js" "$dest/"

  # GR's HTML already uses same-directory relative paths (no rewrite needed)
  # — just append the native-bridge.js script tag right before </body>, after
  # every other script (so it can safely override things like setupPushOptB).
  perl -0pi -e 's{</body>}{  <script src="native-bridge.js"></script>\n</body>}' "$dest/index.html"

  vendor_supabase "$dest"
  inject_boot_debug "$dest"
}

build_en() {
  local dest="$NATIVE/en-app/www"
  echo "Building EN www/ -> $dest"
  rm -rf "$dest"
  mkdir -p "$dest"

  cp "$SAAS/en/app.html" "$dest/index.html"
  cp "$SAAS/en/login.html" "$dest/login.html"
  cp "$SAAS/en/reset.html" "$dest/reset.html" 2>/dev/null || true
  cp "$SAAS/en/privacy.html" "$dest/privacy.html"
  cp "$SAAS/en/terms.html" "$dest/terms.html"
  cp "$SAAS/styles.css" "$dest/"
  cp "$SAAS/config.js" "$dest/"
  cp "$SAAS/en/freemium.js" "$dest/"
  cp "$SAAS/app.js" "$dest/"
  cp "$SAAS/en/suppliers.js" "$dest/"
  cp "$SAAS/usa.js" "$dest/"
  cp "$SAAS/native-bridge.js" "$dest/"

  # EN's HTML normally sits one directory below the shared files (saas/en/
  # referencing saas/styles.css etc. via "../") — now that everything is
  # flattened into one www/ directory, those "../" prefixes must be stripped.
  # perl -pi (not sed -i) — sed's -i takes a mandatory backup-suffix argument
  # on macOS/BSD but not on Linux/GNU, so a single `sed -i -e ...` invocation
  # can't be written portably across both; perl -pi works the same either way.
  perl -pi \
    -e 's{href="\.\./styles\.css"}{href="styles.css"};' \
    -e 's{src="\.\./config\.js"}{src="config.js"};' \
    -e 's{src="\.\./app\.js}{src="app.js};' \
    -e 's{src="\.\./usa\.js}{src="usa.js};' \
    "$dest/index.html"

  perl -0pi -e 's{</body>}{  <script src="native-bridge.js"></script>\n</body>}' "$dest/index.html"

  vendor_supabase "$dest"
  inject_boot_debug "$dest"
}

build_gr
build_en
echo "Done. Run 'npx cap sync' inside native/gr-app and native/en-app to copy these into the ios/android projects."
